name: Generate Resources

on:
  schedule:
    - cron: '0 0 */15 * *'

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Node
        uses: actions/setup-node@v4
        with:
          node-version: 21
          cache: 'npm'

      - name: Install dependencies
        run: npm install

      - name: Generate images
        run: npm run start
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GH_USERNAME: ${{ vars.GH_USERNAME }}
          GH_GRAPHQL_ENDPOINT: ${{ vars.GH_GRAPHQL_ENDPOINT }}

      - name: Commit to the repository
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          FILE_TO_COMMIT: ./output/languages.svg
          DESTINATION_BRANCH: main
        run: |
          if [[ ! $(git status --porcelain) ]]; then
            echo "No changes. Aborting commit and push."
            exit 0
          fi

          export TODAY=$(date -u '+%Y-%m-%d')
          export MESSAGE="chore: regenerate $FILE_TO_COMMIT for $TODAY"
          export SHA=$(git rev-parse $DESTINATION_BRANCH:$FILE_TO_COMMIT)
          export CONTENT=$(base64 -i $FILE_TO_COMMIT)
          
          gh api --method PUT /repos/:owner/:repo/contents/$FILE_TO_COMMIT \
            --field message="$MESSAGE" \
            --field content="$CONTENT" \
            --field encoding="base64" \
            --field branch="$DESTINATION_BRANCH" \
            --field sha="$SHA"
