name: Generate Resources

on:
  schedule:
    - cron: '*/5 * * * *'

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up Node
        uses: actions/setup-node@v3
        with:
          node-version: 21
          cache: 'npm'

      - name: Install dependencies
        run: npm install

      - name: Generate images
        run: npm run start
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          GH_USERNAME: ${{ vars.GH_USERNAME }}
          GH_GRAPHQL_ENDPOINT: ${{ vars.GH_GRAPHQL_ENDPOINT }}

      - name: Commit to the repository
        run: |
          git config --global user.name "franciscodelahoz/github-stats"
          git config --global user.email "github-stats[bot]@franciscodelahoz.github.io"
          git add ./output/languages.svg
          git commit -m '[Bot] Generated resources'
          git push origin main
